@echo off
echo Stopping EventMate Application...

echo Stopping Backend...
for /f "tokens=5" %%a in ('netstat -ano ^| findstr :8082') do taskkill /PID %%a /F

echo Stopping Frontend...
for /f "tokens=5" %%a in ('netstat -ano ^| findstr :3000') do taskkill /PID %%a /F

echo All applications have been stopped.
echo Press any key to exit...
pause >nul